# Generated by Django 2.2.12 on 2022-07-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='user_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
