# Generated by Django 2.2.12 on 2022-07-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220718_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profile',
            field=models.ImageField(blank=True, upload_to='user_profile/'),
        ),
    ]
