# Generated by Django 2.2.12 on 2022-07-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220718_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_profile',
            field=models.ImageField(default='/user_profile/testimonal1.jpg', upload_to='user_profile/'),
        ),
    ]
