# Generated by Django 2.2.12 on 2022-06-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contactusmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribtionModel',
        ),
    ]
