# Generated by Django 2.2.12 on 2022-06-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subscribtionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
