# Generated by Django 2.2.12 on 2022-07-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220620_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribtionModel',
            new_name='SubscriptionModel',
        ),
    ]
