# Generated by Django 2.2.12 on 2022-07-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220709_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=100)),
            ],
        ),
    ]
